name: RHEL 9 STIG - Boot and System

stages:
  stig:
    - name: V-257778
      commands:
        - |
          dnf -y update --security

    - name: V-257779
      commands:
        - |
          cat > /etc/issue <<'EOF'
          You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.
          
          By using this IS (which includes any device attached to this IS), you consent to the following conditions:
          
          -The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.
          
          -At any time, the USG may inspect and seize data stored on this IS.
          
          -Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose.
          
          -This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy.
          
          -Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.
          EOF
          chmod 0644 /etc/issue

    - name: V-257781
      commands:
        - |
          systemctl set-default multi-user.target

    - name: V-257788
      commands:
        - |
          systemctl disable --now debug-shell.service 2>/dev/null || true
          systemctl mask debug-shell.service

    - name: V-257790
      commands:
        - |
          path="$(readlink -f /etc/grub2.cfg 2>/dev/null || true)"; test -n "$path" || path=/boot/grub2/grub.cfg; chgrp root "$path"

    - name: V-257791
      commands:
        - |
          path="$(readlink -f /etc/grub2.cfg 2>/dev/null || true)"; test -n "$path" || path=/boot/grub2/grub.cfg; chown root "$path"

    - name: V-257792
      commands:
        - |
          grubby --update-kernel=ALL --args=vsyscall=none

    - name: V-257793
      commands:
        - |
          grubby --update-kernel=ALL --args=init_on_alloc=1

    - name: V-257794
      commands:
        - |
          grubby --update-kernel=ALL --args=init_on_free=1

    - name: V-257795
      commands:
        - |
          grubby --update-kernel=ALL --remove-args=mitigations=off

    - name: V-257796
      commands:
        - |
          grubby --update-kernel=ALL --args=audit=1

