name: RHEL 9 STIG - Cryptography

stages:
  stig:
    - name: V-258236
      commands:
        - dnf -y reinstall crypto-policies
        - update-crypto-policies --set FIPS

    - name: V-258241
      files:
        - path: /etc/crypto-policies/policies/modules/STIG.pmod
          permissions: "0644"
          content: |
            # Define ciphers and MACs for OpenSSH and libssh
            cipher@SSH=AES-256-GCM AES-256-CTR AES-128-GCM AES-128-CTR
            mac@SSH=HMAC-SHA2-512 HMAC-SHA2-256
      commands:
        - update-crypto-policies --set FIPS:STIG

    - name: V-270177
      commands:
        - dnf -y reinstall crypto-policies
        - update-crypto-policies --set FIPS

    - name: V-270178
      commands:
        - dnf -y reinstall crypto-policies
        - update-crypto-policies --set FIPS

    - name: V-257989
      commands:
        - dnf -y reinstall crypto-policies
        - update-crypto-policies --set FIPS

    - name: V-257991
      commands:
        - dnf -y reinstall crypto-policies
        - update-crypto-policies --set FIPS
